version: '3'
services:
  akura-integration-engine:
    container_name: akura-integration-engine
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    tty: true
    volumes:
      - .:/usr/share/nginx/html/
      - ./nginx.conf/:/etc/nginx/conf.d/
